# Generated by Django 4.0.4 on 2022-07-16 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='variant',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
