# Generated by Django 4.0.4 on 2022-07-16 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_remove_product_variant_product_instoke1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price1',
            field=models.FloatField(default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price2',
            field=models.FloatField(default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price3',
            field=models.FloatField(default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price4',
            field=models.FloatField(default=None, max_length=255, null=True),
        ),
    ]
